### ISSUE TITLE
Error messages X layers over the jobs panel

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation-server-control-panel#114]
![image](https://user-images.githubusercontent.com/57223640/193418175-4c5a1628-1b23-4f37-9e4f-9fa500707de5.png)
![image](https://user-images.githubusercontent.com/57223640/193418165-5c3084dd-9f34-4525-b09f-0f7a1e060fd0.png)

**Comment by Cyberboss** [comment]
Might be fixed with f5731af5a43bdd65223bb61f843766798b7f119d

**Comment by Cyberboss** [comment]
Yes
