### ISSUE TITLE
Option to have the sidebar always expanded

### ISSUE THREAD

**Issue by ike709** [tgstation/tgstation-server-control-panel#129]
It constantly expanding and shrinking when I move my mouse is really annoying and there's _so_ much unused horizontal space anyways

**Comment by Cyberboss** [comment]
Pretty sure this is a config option

**Comment by alexkar598** [comment]
Already a thing

**Comment by Cyberboss** [comment]
![image](https://user-images.githubusercontent.com/8171642/194969196-3b3236f2-16e3-422d-b214-a85ae4c924bc.png)

**Comment by ike709** [comment]
Refer to https://github.com/tgstation/tgstation-server-webpanel/issues/126
