### ISSUE TITLE
Buttons on the side of /app/instances/edit/3/ do not work

### ISSUE THREAD

**Issue by PowerfulBacon** [tgstation/tgstation-server-control-panel#133]
tgs.whatever.com/app/instances/edit/3/

![image](https://user-images.githubusercontent.com/26465327/195171332-ec525314-53e1-4afb-b184-33c2f969aca9.png)

Clicking on these buttons on the left hand side in the firefox browser has no effect.

Reopening the page on fullscreen mode, has different buttons but they still don't work.

![image](https://user-images.githubusercontent.com/26465327/195171722-d1eb04f5-fc9d-4e44-8327-4009ed019fd3.png)

**Comment by Cyberboss** [comment]
Can you repro this and then paste your browser console please (F12)

**Comment by PowerfulBacon** [comment]
Reproduction is pretty easy, just go on the page and it happens (I wasn't the only person to have this happen to).
No logs when I press the button, but these are my total logs (Thought it could be the third party cookie rejection, but it wasnt just me getting this):
[epicfail.txt](https://github.com/tgstation/tgstation-server-webpanel/files/9759428/epicfail.txt)

**Comment by PowerfulBacon** [comment]
Apparently this worked yesterday, but stopped working

**Comment by Crossedfall** [comment]
> Apparently this worked yesterday, but stopped working

It stopped working when the version was bumped. I suspect the fix pushed to correct the layering broke the buttons.

**Comment by Crossedfall** [comment]
I confirm that rolling us back to `4.2.2` // API - `9.6.0` resolves the problem

**Comment by Cyberboss** [comment]
> > Apparently this worked yesterday, but stopped working
> 
> It stopped working when the version was bumped. I suspect the fix pushed to correct the layering broke the buttons.

Grrr

**Comment by Crossedfall** [comment]
Fix confirmed.
