### ISSUE TITLE
TM conflicts should be clearer

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation-server-control-panel#134]
Currently you need to click into the errored job to know what conflicted (and it calls it an internal error btw not a conflict), it should show up more clearly imo

Update to remote was selected and added a new conflicting PR to reproduce

**Comment by Cyberboss** [comment]
Is this better? 
![image](https://user-images.githubusercontent.com/8171642/226739104-fccd950b-ef73-4c91-88e7-a4e0ddc9d085.png)
