### ISSUE TITLE
Update to remote doesn't pull the latest changes from a TM

### ISSUE THREAD

**Issue by Crossedfall** [tgstation/tgstation-server-control-panel#140]
Reproduction steps:

1. TM a PR
2. Commit
3. Update the PR
4. Select `Update to Remote`
5. Commit

Expected: The PR will be retestmerged at the latest commit
Actual: The PR gets  retestmerged at the old commit

---

Having to go through each PR and manually refresh them is an unnecessary time sync and doesn't match up with what the desktop client currently does. The other two options should be used for maintaining current commits.

**Comment by Cyberboss** [comment]
Update to Remote still won't do this on its own but that's by design. When entering the repo page now the test merges and update button should be in the default desired state (update branch and update all TMs to HEAD)
