### ISSUE TITLE
channel.json 404 (Not Found)

### ISSUE THREAD

**Issue by azenkov** [tgstation/tgstation-server-control-panel#152]
In production mode for some reason index.html is requesting channel.json, doesnt find it and throws an alert about fallback of some sort. Maybe I misconfigured it somehow?

**Comment by Cyberboss** [comment]
`channel.json` is served from the main server with some configuration. Is your server able to start without errors?

**Comment by azenkov** [comment]
from which server? I am using nginx to server the panel. I dont see where channel.json would come from

**Comment by Cyberboss** [comment]
To be clear, you are hosting [tgstation-server](https://github.com/tgstation/tgstation-server) right? Which is the main server this client is for.

**Comment by azenkov** [comment]
Yes. I do. But if I understand correctly it just sends a redirect to the panel if there is no API headers?

**Comment by Cyberboss** [comment]
Yes, the panel should be being hosted under `/app` if you have it enabled.
You should be able to view `channel.json` by navigating to `/app/channel.json`. Are you able to do that?

What version of TGS are you using for reference?

**Comment by azenkov** [comment]
/app/channel.json gives me 404. And I dont see such file in the /dist folder. Is this something  TSG is supposed to generate? Im on 5.16

**Comment by Cyberboss** [comment]
It's an API endpoint hosted by TGS itself, yes. Do you have `ControlPanel:Enable` set to true in your config?

**Comment by Cyberboss** [comment]
If yes, please upload your TGS log files.

**Comment by azenkov** [comment]
[tgs_logs_config.zip](https://github.com/tgstation/tgstation-server-webpanel/files/12755417/tgs_logs_config.zip)
Here are the logs and config files.

**Comment by alexkar598** [comment]
Make sure the X-Webpanel-Fetch-Channel header is proxied

**Comment by azenkov** [comment]
Wouldn't nginx proxy all headers?

**Comment by Cyberboss** [comment]
Is your TGS hosted at the root of your site? i.e. `xxx.yyy.zzz/app`?

**Comment by Cyberboss** [comment]
The linked PR above is a TGS release I'm pushing with some additional logging. Hopefully, it will help diagnose the issue here.

**Comment by azenkov** [comment]
> Is your TGS hosted at the root of your site? i.e. `xxx.yyy.zzz/app`?

yes

**Comment by Cyberboss** [comment]
Okay, hopefully this logging reveals more. I'll let you know when the
update is out

**Comment by Cyberboss** [comment]
It's out now, try updating and attempting to load the control panel and then send me the logs.

Also, can you set the MicrosoftLogLevel config to Warning please? It's very spammy and makes decoding the logs harder than it needs to.

**Comment by azenkov** [comment]
[tgs-20231001.log](https://github.com/tgstation/tgstation-server-webpanel/files/12775895/tgs-20231001.log)
here is it. To make it work I had to put a workaround in nginx config:
        location /app/channel.json {
                proxy_pass http://127.0.0.1:5000;
                break;
        }

**Comment by Cyberboss** [comment]
I don't see any control panel logs in the new version, it looks like you turned down both `LogLevel` and `MicrosoftLogLevel`. If it's working now though I suppose this is dealt with.

**Comment by azenkov** [comment]
Sorry. I still don't understand how I can configure tgs panel to be hosted on a URL different from /app. It seems like /app is hardcoded. Can someone plase explain me.

**Comment by Cyberboss** [comment]
Yes, it is hard coded. Not meant to be changed

**Comment by Cyberboss** [comment]
You can move the entire server to a subpart but the /app suffix must remain

**Comment by azenkov** [comment]
This is what I ended up with. Had to rewrite URLS

        location = /tgs-panel {
                rewrite /tgs-panel / break;
                proxy_pass http://127.0.0.1:5000;
        }

        location ~ ^/tgs-panel/(.*)$ {
                rewrite ^/tgs-panel/(.*)$ /$1 break;
                proxy_pass http://127.0.0.1:5000;
        }
