### ISSUE TITLE
Feature request: send message to server from webpanel

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation-server-control-panel#158]
There was a feature in the old tgstation service to send a message to the server from the panel where it would appear in game as from "Server:" <alert>

This was useful to inform people of things such as a restart or to shitpost via the tgs instance.

**Comment by Cyberboss** [comment]
Needs https://github.com/tgstation/tgstation-server/issues/138

**Comment by Cyberboss** [comment]
Fixed in e3b69f513b01c7d5ed40f27cdf6b5670f486dabb
