### ISSUE TITLE
Restart popup has no text

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation-server-control-panel#161]
Reproduction steps

Log in to tgs campbell

Click restart button.

????
![picutre of tgs admin page for restarts of the server instance the popup confirming a restart is completely empty but for its title.](https://github.com/tgstation/tgstation-server-webpanel/assets/2544323/84d6fdda-5d61-4951-9c24-f734e00dfc26)

**Comment by Cyberboss** [comment]
I was lazy, alright?
