### ISSUE TITLE
ServerClient#login's deduplication is too agressive

### ISSUE THREAD

**Issue by alexkar598** [tgstation/tgstation-server-control-panel#9]
The deduplication system can fail in the following way:

1. Make request A with credentials A
2. Credentials A gets saved to CredentialsProvider
3. Request A begins executing
4. Make request B with credentials B
5. Credentials B gets saved to CredentialsProvider
6. Request B is cancelled and awaits the result of request A to deduplicate
7. Request A completes

8. Request A **and** B resolve to the output of request A but the CredentialsProvider contains Credentials B

Possible solutions:
- Set CredentialsProvider only when a request completes successfully
- Reject request B because Credentials B do not match Credentials A

**Comment by Cyberboss** [comment]
Closing this because I've revisited this code several times since this issue was opened. It shouldn't still be prevalent
